version: 2

aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-deps-cache
    key: deps-cache-{{ checksum "package-lock.json" }}

  - &save-deps-cache
    key: deps-cache-{{ checksum "package-lock.json" }}
    paths:
      - ~/string-json-template-language/node_modules

  # -------------------------
  #  ALIASES: Branch Filters
  # -------------------------
  - &filter-only-master
    branches:
      only: master
  - &filter-only-semantic-pr
    branches:
      only:  /^(pull|dependabot|fix|feat)\/.*$/
  - &filter-only-fork-pr
    branches:
      only:  /^pull\/.*$/

defaults: &defaults
  working_directory: ~/string-json-template-language
  docker:
    - image: circleci/node:10

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - run: npm install codecov
      - run: npm test
      - run: ./node_modules/.bin/codecov
      - save_cache: *save-deps-cache

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - run: npm run build
      - save_cache: *save-deps-cache

  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - run: npm run build
      - run: npx semantic-release
      - save_cache: *save-deps-cache

workflows:
  version: 2
  analysis:
    jobs:
      - test:
          filters: *filter-only-semantic-pr
      - build:
          filters: *filter-only-semantic-pr
          requires:
            - test

  release:
    jobs:
      - test:
          filters: *filter-only-master
      - build:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - test
            - build
      - release:
          filters: *filter-only-master
          requires:
            - hold